### ISSUE TITLE
When the path contains Chinese characters, the application fails to run.

### ISSUE THREAD

**Issue by git20210101** [agracio/edge-js#232]
When the path contains Chinese characters, the application fails to run.

**Comment by agracio** [comment]
Could you give me some examples.

**Comment by agracio** [comment]
I thought this issue was already fixed by one of old PRs, let me take a closer look. 
And do not worry about your english I am sure we can communicate, Google translate is doing a perfect job.

**Comment by agracio** [comment]
I am getting a different exception, what version of nuget are you using? Old one is called `Edge.js` and mine is published as `EdgeJs`

**Comment by agracio** [comment]
Found PR that was supposed to fix the problem: https://github.com/tjanczuk/edge/pull/555. Maybe it did not fix all the issues and some characters are still not supported.

**Comment by agracio** [comment]
Depending on what kind of non-english characters I use in path it blows up with different exceptions. Not sure it can be fixed very easily.

**Comment by git20210101** [comment]
The project framework is .NET Framework 4.8, and the Edge.js version is 9.3.0.0. I have also tried integrating the latest code directly into the project, but the same issue persists.

I believe that solving this problem might require recompiling libnode.dll. Here is the relevant code:
`argv.Add(shortPath.ToString());
argv.Add(string.Format("-EdgeJs:{0}", Path.Combine(edgeDirectory, "EdgeJs.dll")));
nodeStart(argv.Count, argv.ToArray());`

The argv parameters print correctly, so the issue must be with the nodeStart function.

**Comment by agracio** [comment]
I am using EdgeJs 20.12.3 - this is the nuget package from `edge-js`, Edge.js nuget package is from old `edge`.  Encountering the problem above.

**Comment by agracio** [comment]
Possible fix for that particular issue changing 

```cs
[DllImport("kernel32.dll", EntryPoint = "LoadLibrary")]
static extern int LoadLibrary([MarshalAs(UnmanagedType.LPStr)] string lpLibFileName);`
```
to 

```cs
[DllImport("kernel32.dll", EntryPoint = "LoadLibrary")]
static extern int LoadLibrary( [MarshalAs(UnmanagedType.LPUTF8Str)] string lpLibFileName);`
```

**Comment by agracio** [comment]
This is the file you should be looking at: https://github.com/agracio/edge-js/blob/master/src/double/Edge.js/dotnet/EdgeJs.cs

**Comment by git20210101** [comment]
I am not using the wrong files, but the UnmanagedType enumeration in the .NET Framework does not have the LPUTF8Str option. Since using version 20.12.3 from NuGet did not work, I downloaded the code from GitHub to use it. Therefore, my responses regarding the version issues were a bit confusing.
![image](https://github.com/user-attachments/assets/53595605-ec15-499a-964b-5b239f1b6ffe)

**Comment by agracio** [comment]
Could you tell me what exception you getting when using 20.12.3

**Comment by agracio** [comment]
I encountered this issue when using chinese characters that you provided: https://github.com/agracio/edge-js/issues/232#issuecomment-2476120677

**Comment by git20210101** [comment]
I don't know if you can't see the images, so I'll copy the error message for you.
` Microsoft Windows [版本 10.0.22631.4460]
(c) Microsoft Corporation。保留所有权利。

C:\Users\Zero\Desktop\测试\Debug>ConsoleApp1.exe
node:internal/modules/cjs/loader:1146
  throw err;
  ^

Error: Cannot find module 'C:\Users\Zero\Desktop\����\Debug\edge\DOUBLE~1.'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.12.2

C:\Users\Zero\Desktop\测试\Debug> `

You can see that the word "测试" is garbled

**Comment by agracio** [comment]
This should happen on earlier versions before https://github.com/tjanczuk/edge/pull/555 was merged, very strange.

**Comment by agracio** [comment]
This is a complicated issue to resolve, so not sure when or if I am able to figure it out.
Possibly https://github.com/tjanczuk/edge/pull/555 needs to be applied to more paths but it wont be easy.

**Comment by agracio** [comment]
Could you start a fresh project using 20.12.3 and confirm that you getting `Error: Cannot find module 'C:\Users\Zero\Desktop\����\Debug\edge\DOUBLE~1.'` to make sure it is not caused by some lingering artefacts.

**Comment by git20210101** [comment]
I'm not entirely clear about the logic in the code, but is it possible to use a method similar to SetAssemblyDirectory to set edgeDirectory to point to a different path? This way, I could achieve the desired functionality by copying files. I have tried directly assigning a value to edgeDirectory in SetAssemblyDirectory, but the program does not run correctly.


The error I sent you was generated from a new project that only uses Edge.js. After building the project successfully, placing the debug/release folder in a Chinese-named directory causes this issue. It took me a long time to figure out that this was the cause of the error.

**Comment by agracio** [comment]
Why do you think that the issue is `edgeDirectory `? 
It looks like you having an issue loading `edge/double_edge.js` which is using `AssemblyDirectory` plus a patch from https://github.com/tjanczuk/edge/pull/555. 
Maybe the patch is that actually causes the problems, since you locale is set to Chinese maybe the patch should be ignored and instead `argv.Add(AssemblyDirectory + "\\edge\\double_edge.js");` should be used.
I am not sure myself tbh since we are getting different errors on our systems, the only difference I can think of is your system locale vs my locale.

**Comment by git20210101** [comment]
I tried this method yesterday. Even after removing the patch and using the original values, the same issue persists.

**Comment by agracio** [comment]
It is almost impossible for me to troubleshoot since we are getting different errors on our systems.

**Comment by git20210101** [comment]
> Why do you think that the issue is `edgeDirectory `? It looks like you having an issue loading `edge/double_edge.js` which is using `AssemblyDirectory` plus a patch from [tjanczuk/edge#555](https://github.com/tjanczuk/edge/pull/555). Maybe the patch is that actually causes the problems, since you locale is set to Chinese maybe the patch should be ignored and instead `argv.Add(AssemblyDirectory + "\\edge\\double_edge.js");` should be used. I am not sure myself tbh since we are getting different errors on our systems, the only difference I can think of is your system locale vs my locale.
> 
> Try recompiling Edge.dll without the patch and just using `argv.Add(AssemblyDirectory + "\\edge\\double_edge.js");`, I am curious what will happen then.

edgeDirectory is not the issue. I just want to try another approach to solve this problem. Specifically, I plan to copy all Edge.js-related files to a temporary directory, which will not contain any Chinese characters. Then, I can load and use these files from the temporary directory.

**Comment by agracio** [comment]
You can compile your own libnode.dll by downloading Node.js source from https://nodejs.org/en/download/source-code and then running `vcbuild.bat release x64 dll` from its root, but that would get you the same libnode.dll that EdgeJs nuget uses.

**Comment by git20210101** [comment]
The issue has been resolved. Using relative paths when passing parameters works fine.
` argv.Add(@"edge\double_edge.js");
 argv.Add("-EdgeJs:EdgeJs.dll");

 nodeStart(argv.Count, argv.ToArray());`

**Comment by agracio** [comment]
I am happy it is resolved for you however I am not sure introducing this into the main repo would not cause problems for other people.

**Comment by agracio** [comment]
I released a new Nuget package that resolves the issue for me, not sure it will resolve it for you since we were getting different errors.
